### ISSUE TITLE
关于Train.py

### ISSUE THREAD

**Issue by JJYdesu** [kiva12138/CubeMLP#2]
作者您好，train.py第12行引入的DataLoaderLocal，缺少了这个文件，代码无法跑起来，谢谢。

**Comment by JJYdesu** [comment]
> 作者您好，train.py第12行引入的DataLoaderLocal，缺少了这个文件，代码无法跑起来，谢谢

**Comment by TrulyLi** [comment]
train.py第12行引入的DataLoaderLocal，缺少了这个文件,谢谢

**Comment by kiva12138** [comment]
已经加入
