### ISSUE TITLE
question about ablation study

### ISSUE THREAD

**Issue by sunjieemm** [kiva12138/CubeMLP#5]
Hi, I have confused about the representation that "We can infer from the results that the sequential-mixing (MLP-L) and channel-mixing (MLP-D) play more important roles than modality mixing (MLP-M)" in 5.2 ablation study. As the demonstration of table 3, Model 5's most grades are worse than Model 4, shouldn't it mean that MLP-M is more important than MLP-D?

**Comment by kiva12138** [comment]
Thanks for the careful question. You are right for the ablation study issue. Between paris (Model2, Model3) and (Model4, Model5), the performance difference is indeed somewhat subtle. And the representations in the paper is confusing too. We will try our best to coordinate with ACM for whether we could revise that.
