### ISSUE TITLE
Substandard performance

### ISSUE THREAD

**Issue by a-sdsaj** [kiva12138/CubeMLP#8]
Hello, I ran the program with the parameters you gave in the readme and the F1 is 74.56 on the mosi dataset. Looking forward to your reply, thanks

**Comment by kiva12138** [comment]
The F1 of 74 is quite not normal. Generally speaking, the actual performance would be better than those in the paper, as posted by others. Maybe the reason the different platform and package version. And I think you can try to tune some hyper paramters, e.g., lr, batch size, hidden size, which may bring the performance higher.  Furthermore, we find the dataset processed by Declare lab is better (`https://github.com/orgs/declare-lab/repositories`). I think you can take a try for that.

**Comment by a-sdsaj** [comment]
Thanks for your help, I re-downloaded the bert model and the F1 accuracy is 84.3, next I will try to adjust the hyperparameters. Good luck with your research!
